version: '3.7'
services:
  allure-server:
    image: custom-allure-server:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/allure
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - 8080:8080
    volumes:
      - /Quest/allure-data/ext:/ext:rw
      - /Quest/allure-data/allure-server-store:/allure:rw
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: allure
    ports:
      - 5432:5432
    volumes:
      - /Quest/allure-data/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
